[package]
name = "rt-audio-disk-stream"
version = "0.0.0"
authors = ["Billy Messenger <BillyDM@protonmail.com>"]
edition = "2018"
license = "GPL-3"
keywords = ["audio", "io", "disk", "stream"]
categories = ["multimedia::audio"]
description = "Realtime disk streaming IO for audio (placeholder)"
documentation = "https://docs.rs/rt-audio-disk-stream"
repository = "https://github.com/RustyDAW/rt-audio-disk-stream"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "core",
    "symphonia",
    "examples/demo_player",
]

[features]
default = ["symphonia"]
symphonia = ["rt-audio-disk-stream-symphonia"]

[dependencies]
rt-audio-disk-stream-core = { path = "core" }
rt-audio-disk-stream-symphonia = { path = "symphonia", optional = true }
